# Output 输出
resolution = [1920, 1080]
fps = 60
sampleCount = 8
fxaa = false
hardwareAccel = true
hevc = false
mpeg4 = false
# customEncoder = ""
fileNameFormat = "%date% %time% %info.name%_%level_prefix%"
dynamicBitrateControl = true
bitrate = "28"
endingLength = 0.0
playStartTime = 0.0
# playEndTime = 
renderLoading = true


# Player 玩家
# playerAvatar = ""
playerName = "HLMC"
playerRks = 16.0
challengeColor = "rainbow" # white green blue red golden rainbow
challengeRank = 3


# Graphics 图像
# res_pack_path = ""
chartDebugLine = 0.0
chartDebugNote = 0.0
chartRatio = 1.0
noteScale = 1.0

renderLine = true
renderLineExtra = true
renderNote = true
renderDoubleHint = true
renderUiPause = true
renderUiName = true
renderUiLevel = true
renderUiScore = true
renderUiCombo = true
renderUiBar = true
renderBg = true
preserveFramebuffer = false
renderBgDim = true
particle = true
renderExtra = true
renderBlockArea = true
blockAreaClockOffset = 0.0

aggressiveChart = true
aggressiveNote = false
aggressiveParticle = false

bgBlurriness = 80.0
watermark = ""
combo = "AUTOPLAY"
maxParticles = 5000 # 5000 25000 200000

# Audio 音频
hires = false
loudnessEqualization = false
audioMixMode = "culling" # traditional culling fft

volumeMusic = 0.5
volumeSfx = 0.4
forceLimit = true
limitThreshold = 0.5


# Other 其他
allGood = false
allBad = false
judgeOffset = 0.0
difficulty = ""
fade = 0.0
speed = 1.0
alphaTint = false
roman = false
chinese = false
